

target 'FirebaseVIN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks! 使用的依赖库文件

  pod 'Firebase/CoreOnly'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

end